### ISSUE TITLE
html templating/css styling, responsiveness, adaptability

### ISSUE THREAD

**Issue by constantstress** [Hona/TempusHub#50]
labels:
* `For:Frontend`
* `Impacts: UI/UX`
* `Type: Idea`

----

As I visit https://tempushub.xyz/topplayersonline or https://tempushub.xyz/players on my phone (or set the width of the screen to `960px` or less in the browser developer tools)  table rows behave undesirably. 

Good
(screen width `961px` or more)
![image](https://github.com/Hona/TempusHub/assets/149433905/a6ffd62d-3eb3-4f22-9608-4137903979e9)
Bad
(screen width `960px` or less)
![image](https://github.com/Hona/TempusHub/assets/149433905/92cf67e6-459d-466f-8d38-4982b3ee3e7f)
I expect both tables to be identical. This is not the case

----
I suggest represent player entries not as table rows inside a table, but as flex items inside a container. Maybe this table solution is also curable, but flex items inside a container seems intuitive.
Also connect link might be not shown for the small screens to free space(do mobile visitors really need it?) . Or show it as an svg or some small picture.

**Comment by constantstress** [comment]
Screenshot for the `/players` page
This one has only 3 columns (`/topplayersonline` page has 5), but behaves the same.
![image](https://github.com/Hona/TempusHub/assets/149433905/8e190089-07b5-4147-810e-515c09ddf01c)

**Comment by Hona** [comment]
This is intentional responsive design for mobile.
The new [TempusHub2](https://github.com/Hona/TempusHub2) is where all new dev work will happen.

Thank you for raising this issue
